"""添加用户角色字段

Revision ID: 645cc0225cc3
Revises: 6ffbb9a77890
Create Date: 2025-03-17 19:48:35.353787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '645cc0225cc3'
down_revision = '6ffbb9a77890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户姓名'),
    sa.Column('pwd', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('salt', sa.String(length=32), nullable=True, comment='salt'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', mysql.VARCHAR(length=40), nullable=False, comment='用户姓名'),
    sa.Column('pwd', mysql.VARCHAR(length=255), nullable=True, comment='密码'),
    sa.Column('salt', mysql.VARCHAR(length=32), nullable=True, comment='salt'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
